### ISSUE TITLE
?

### ISSUE THREAD

**Issue by BokChoyWarrior** [lizziehand/boolean-uk-react-gmail-state#1]
Hi lizziehand,

It appears that you open many repositories but seem to abandon each of them rather quickly.

Is there any chance you'll be sticking to one project soon?

I am anxiously awaiting to see you put what you have learned to good use!

Regards,
Harvey

**Comment by lizziehand** [comment]
Ello ello!

Haha I know we do a different exercise each day on the course I'm doing so they are indeed abandoned very quickly! Here's a longer javascript project we did: https://github.com/lizziehand/boolean-uk-js-project .Can't wait to get to get my theeth stuck into some longer/more interesting projects actually! 

Just had a look at your code and it looks super interesting!! Seems way more advanced than what I'm doing but maybe that's maybe I don't understand half of it.

I can see your doing a JS project? :heart_eyes:  Are you teaching yourself off the internet?

Lizzie

**Comment by BokChoyWarrior** [comment]
Morning!

Oh yeah I saw that one, looks pretty interesting actually. It's a blog kind of thing?

I also don't blame you for not understanding my project because it's my first javascript project so I'm half fighting the language every step of the way. 😭 But yeah I'm teaching myself more or less

I was wondering, do you have discord or slack or something so we can talk properly? I didnt realise that github doesn't have a chat feature the other day hahaha it's literally just for coding!

**Comment by lizziehand** [comment]
Yeah essentially- you can write,edit,view, comment posts etc. Super interesting but I can't wait til I can do my own thing! Are they giving you projects at your scheme?

Haha Javascript is the best! It looks pretty good to me! You'll have to explain how it works to me when it's finished. It's so sick your teaching yourself. I've got some good resources too from when I taught myself if you need anything.

Nope it doesn't does ittt 😪  Yess good idea! I've got discord, my username is #4295. :blush:

**Comment by BokChoyWarrior** [comment]
You didn't send your discord username properly lol, add `Gucci#4945` 

Mmmmm yeah I bet you cant, but that sounds pretty cool so far. I made one of those in flask just for learning purposes 😉

Yeah defo maybe you could help out on it a little? I have so much to do and people aren't working because they haven't been paid. Quite depressing actually
